# Time should be in UTC
courts:
  # Charlotte
  - tenant_id: "8b818dae-aacb-4ea3-aa7b-0e77b1149c85"
    sport_id: "PADEL"
    time_windows:
      - start: "15:00"
        end: "17:00"
  # - tenant_id: "9fea856e-7d1a-4cae-9831-79015318967b"
  #   sport_id: "PADEL"
  #   time_windows:
  #     - start: "15:00"
  #       end: "17:00"
